### ISSUE TITLE
Microcontroller Demo

### ISSUE THREAD

**Issue by crsz20** [DallasFormulaRacing/DashboardDisplay#22]
- Article: [Develop on Arm Cortex M4](https://wiki.st.com/stm32mpu/wiki/Getting_started/STM32MP1_boards/STM32MP157x-DK2/Develop_on_Arm%C2%AE_Cortex%C2%AE-M4/Install_the_IDE)
- These three article pages will lead to a demo program that uses OpenAMP for synchronizing/messaging with the Cortex A7.
- The Demo program runs a TTY for connecting to a serial console.

**Subtasks**
- [ ] Install CubeIDE
- [ ] Download the CubeMP1 package
- [ ] Run demo program

**Definition of Done**
- [ ] Documentation
- [ ] Running program with a functional TTY
